### ISSUE TITLE
Nodes that have failed to load

### ISSUE THREAD

**Issue by caslix** [Isi-dev/ComfyUI-UniAnimate#1]
Hello! How can I upload missing nodes if they are not in the Manager? Thanks!

![Screenshot_1](https://github.com/user-attachments/assets/9c8ef0a2-4bd2-4d2b-b01d-4880f3a2da6a)

![Screenshot_2](https://github.com/user-attachments/assets/bc404ece-6c6f-4ecc-9994-8a6c8fc44f86)

**Comment by caslix** [comment]
The code is not working. The files have errors, for example: <<<<<<<< HEAD

**Comment by caslix** [comment]
That's exactly how it's done. Look at the contents of many files, they have incomprehensible strings, for example: 
https://github.com/Isi-dev/ComfyUI-UniAnimate/blob/main/__init__.py

---------------------------------------------------------------------------------------
<<<<<<< HEAD
from .uniAnimate_Inference import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

=======
from .uniAnimate_Inference import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

>>>>>>> 626e7afc02230297b6f553675ea1c32c29971314
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
---------------------------------------------------------------------------------------

Therefore, there is an error in the console:

![Screenshot_1](https://github.com/user-attachments/assets/cc3a6c07-ea83-466d-983a-06c5212a17ca)

Maybe you uploaded the wrong code?

**Comment by Isi-dev** [comment]
> That's exactly how it's done. Look at the contents of many files, they have incomprehensible strings, for example: https://github.com/Isi-dev/ComfyUI-UniAnimate/blob/main/__init__.py
> 
> ## HEAD
> [626e7af](https://github.com/Isi-dev/ComfyUI-UniAnimate/commit/626e7afc02230297b6f553675ea1c32c29971314)
> Therefore, there is an error in the console:
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/94461976/355202449-cc3a6c07-ea83-466d-983a-06c5212a17ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODI0MzEsIm5iZiI6MTcyMjg4MjEzMSwicGF0aCI6Ii85NDQ2MTk3Ni8zNTUyMDI0NDktY2MzYTZjMDctZWE4My00NjZkLTk4M2EtMDZjNTIxMmExN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE4MjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYWMxNDQyYTQ3ZTMyZGJlMWYzZTI5MjgzNDY0ZGRiODJjZTU4ZjhjNDJiYzY0NDcxMWE5NTVmZTkzZGY0ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GQ9zivRzV6BuVOZrw4KesFr9gFy8764JdGVFxPtoOxM)
> 
> Maybe you uploaded the wrong code?

Thanks for bringing this up. It seems there was a merge conflict after I made a few changes and tried updating from my local repository. I will rectify it and let you know when I am done.

**Comment by Isi-dev** [comment]
I just finished re-uploading all the files. You can clone the repository again and please let me know if you encounter any issue. Sorry for the inconveniences.

**Comment by caslix** [comment]
Thanks, everything is working now! But on the regular version. 
On the portable version an error occurs: use_libuv was requested but PyTorch was build without libuv support.

**Comment by caslix** [comment]
Yes, I recently updated the dependencies of the ComfyUI Portable, and the latest version of torch=2.4 was installed.

Thanks for the help!
