### ISSUE TITLE
Only output noise

### ISSUE THREAD

**Issue by audioseb** [Isi-dev/ComfyUI-UniAnimate#5]
Hi,
Seems awsome but i only get noise on the output
![vid_00001](https://github.com/user-attachments/assets/fac6c580-858e-4662-9a78-47c550f5ec33)
Tryed different settings but doesn't work for me and no error messages in log
++

**Comment by Isi-dev** [comment]
Sorry about the noisy output. I have not encountered this issue, but let's see if we can resolve it. Please can you tell me about your pytorch version and your OS, and I will also like to see the output of your command line interface from the moment the workflow starts. Did you also try the img repose workflow?
